version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - node-app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - mongodb_data:/data/db

networks:
  node-app:

volumes:
  mongodb_data:
